pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Scripts Building'
            }
        }
        stage('Test') {
            steps {
                echo 'Scripts Testing'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Scripts Deploying'
            }
        }
    }
}
